# Portuguese (Portugal) translations for PROJECT.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-04 18:37-0400\n"
"PO-Revision-Date: 2014-09-04 18:39-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: pt_PT <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: gateone/applications/docker/app_docker.py:117
#, python-format
msgid "Active Docker Plugins: %s, "
msgstr "Ativa Docker Plugins: %s , "

#: gateone/applications/docker/app_docker.py:220
msgid ""
"User is not allowed to use the docker application.  Skipping post-"
"authentication functions."
msgstr "O usuário não tem permissão para usar o aplicativo estivador. Ignorando as funções de pós-autenticação."

#: gateone/applications/docker/app_docker.py:295
msgid "The test_docker WebSocket action was called successfully!"
msgstr "A ação test_docker WebSocket foi chamado com sucesso!"

#: gateone/applications/docker/app_docker.py:297
#: gateone/applications/example/app_example.py:439
#, python-format
msgid "Here's what was recieved: %s"
msgstr "Aqui está o que foi recebido: %s"

#: gateone/applications/docker/app_docker.py:331
msgid "// This is Gate One's Docker application settings file.\n"
msgstr "// Este é o arquivo de configurações do aplicativo do Gate One Docker. \ N"

#: gateone/applications/example/app_example.py:68
msgid "Doesn't do anything (just an example from the example app)."
msgstr "Não faz nada (apenas um exemplo do app exemplo)."

#: gateone/applications/example/app_example.py:99
#, python-format
msgid "%s denied access to the 'test_example' function by policy.upn"
msgstr "%s negado o acesso à função "test_example" por policy.upn"

#: gateone/applications/example/app_example.py:154
#, python-format
msgid "%s denied access to the Example application by policy.upn"
msgstr "%s negado o acesso ao aplicativo por exemplo policy.upn"

#: gateone/applications/example/app_example.py:255
#, python-format
msgid "Active Example Plugins: %s, "
msgstr "Ativa Exemplo Plugins: %s , "

#: gateone/applications/example/app_example.py:358
msgid ""
"User is not allowed to use the Example application.  Skipping post-"
"authentication functions."
msgstr "O usuário não tem permissão para usar o aplicativo exemplo. Ignorando as funções de pós-autenticação."

#: gateone/applications/example/app_example.py:437
msgid "The test_example WebSocket action was called successfully!"
msgstr "A ação test_example WebSocket foi chamado com sucesso!"

#: gateone/applications/example/app_example.py:473
msgid "// This is Gate One's Example application settings file.\n"
msgstr "// Este é o arquivo de configurações do aplicativo Exemplo do Gate One. \ N"

#: gateone/applications/file_transfer/app_file_transfer.py:110
#: gateone/applications/terminal/policy.py:264
#, python-format
msgid "%s denied access to the Terminal application by policy.upn"
msgstr "%s negado o acesso ao aplicativo Terminal policy.upn"

#: gateone/applications/file_transfer/app_file_transfer.py:169
#, python-format
msgid "Active File Transfer Plugins: %s, "
msgstr "Plugins de transferência de arquivos ativos: %s , "

#: gateone/applications/file_transfer/app_file_transfer.py:183
#: gateone/applications/terminal/app_terminal.py:280
msgid "Got exception trying to initialize the {0} plugin:"
msgstr "Tem exceção tentando inicializar a {0} plugin:"

#: gateone/applications/file_transfer/file_utils.py:36
msgid ""
"Could not import lzma module.  You probably need to run 'sudo pip install"
" backports.lzma'.  If you get errors you'll need to install the libzma-"
"dev package and re-run the pip command."
msgstr "Não foi possível importar módulo lzma. Você provavelmente precisará executar "sudo pip instalar backports.lzma '. Se você obter erros que você precisa para instalar o pacote libzma-dev e execute novamente o comando pip."

#: gateone/applications/file_transfer/file_utils.py:99
msgid "Removing because {path} is larger than {human_size}: {fp}"
msgstr "Removendo porque {caminho} é maior que {human_size}: {fp}"

#: gateone/applications/file_transfer/file_utils.py:105
msgid "Could not delete {fp} ({e})"
msgstr "Não foi possível excluir {fp} ({e})"

#: gateone/applications/file_transfer/file_utils.py:128
msgid "Removing file due to age (>{max_age} old): {file_path}"
msgstr "Remoção de arquivos devido à idade (> {} max_age de idade): {} caminho_arquivo"

#: gateone/applications/file_transfer/protocol.py:386
msgid "{instance_name}._process_queue(): No action registered for '{action}'"
msgstr "{} Nome_instância ._ process_queue (): Nenhuma ação registrada para '{ação}'"

#: gateone/applications/file_transfer/protocol.py:393
msgid "{instance_name}._process_queue(): got invalid message: {message}"
msgstr "{} Nome_instância ._ process_queue (): tem mensagem inválida: {mensagem}"

#: gateone/applications/file_transfer/plugins/protocol_dns/protocol_dns.py:95
msgid "Error: dnspython is not installed."
msgstr "Erro: dnspython não está instalado."

#: gateone/applications/file_transfer/plugins/protocol_ftp/protocol_ftp.py:96
#: gateone/applications/file_transfer/plugins/protocol_ftp/protocol_ftp.py:136
msgid "Error retrieving {url}: {err}"
msgstr "Recuperação de erro {url}: {} err"

#: gateone/applications/file_transfer/plugins/protocol_http/protocol_http.py:132
msgid "Fetching {log_url} ({human_size})"
msgstr "Buscando {log_url} ({} human_size)"

#: gateone/applications/file_transfer/plugins/protocol_http/protocol_http.py:135
msgid "Error retrieving {log_url}: {err}"
msgstr "Recuperação de erro {log_url}: {} err"

#: gateone/applications/file_transfer/plugins/protocol_http/protocol_http.py:141
msgid "{log_url} fetched successfully."
msgstr "{} Log_url buscado com sucesso."

#: gateone/applications/terminal/app_terminal.py:57
msgid ""
"If enabled, logs of user sessions will be saved in "
"<user_dir>/<user>/logs.  Default: Enabled"
msgstr "Se ativado, os registros de sessões de usuário serão salvas em <user_dir> / <usuário> / logs. Padrão: Ativado"

#: gateone/applications/terminal/app_terminal.py:64
msgid "If enabled, logs of user sessions will be written to syslog."
msgstr "Se ativado, os registros de sessões de usuário serão gravados para syslog."

#: gateone/applications/terminal/app_terminal.py:70
msgid ""
"Wrap terminals with dtach. Allows sessions to be resumed even if Gate One"
" is stopped and started (which is a sweet feature)."
msgstr "Enrole terminais com dtach. Permite que as sessões sejam retomadas, mesmo Gate One é parado e iniciado (que é uma característica doce)."

#: gateone/applications/terminal/app_terminal.py:77
msgid "Kill any running Gate One terminal processes including dtach'd processes."
msgstr "Mate qualquer execução Gate One processos terminais, incluindo processos dtach'd."

#: gateone/applications/terminal/app_terminal.py:263
#, python-format
msgid "Active Terminal Plugins: %s, "
msgstr "Ativa Terminal Plugins: %s , "

#: gateone/applications/terminal/app_terminal.py:406
msgid ""
"User is not allowed to use the Terminal application.  Skipping post-"
"authentication functions."
msgstr "O usuário não tem permissão para usar o aplicativo Terminal. Ignorando as funções de pós-autenticação."

#: gateone/applications/terminal/app_terminal.py:440
#: gateone/applications/x11/app_x11.py:720
msgid "Path to icon ({icon}) for command, '{cmd}' could not be found."
msgstr "Caminho para o ícone ({} ícone) para o comando, '{cmd}' não pôde ser encontrado."

#: gateone/applications/terminal/app_terminal.py:511
msgid "You're missing the 'commands' setting!"
msgstr "Você está perdendo a configuração 'comandos'!"

#: gateone/applications/terminal/app_terminal.py:530
#: gateone/applications/terminal/app_terminal.py:577
#, python-format
msgid "Bad font in fonts dir (missing Font Family in name table): %s"
msgstr "Bad fonte em fontes dir (faltando Família de fontes na tabela nome): %s"

#: gateone/applications/terminal/app_terminal.py:803
msgid ""
"Warning: Terminals are closing too fast.  If you see this message "
"multiple times it is likely that the configured command is failing to "
"execute.  Please check your server settings."
msgstr "Aviso: Os terminais estão fechando muito rápido. Se você ver esta mensagem várias vezes, é provável que o comando configurado não está a executar. Por favor, verifique as configurações do servidor."

#: gateone/applications/terminal/app_terminal.py:813
#, python-format
msgid ""
"Terminals are closing too quickly after being opened (command: %s).  "
"Please check your 'commands' (usually in settings/50terminal.conf)."
msgstr "Terminais estão fechando muito rapidamente após a abertura (comando: %s ). Por favor, verifique seus 'comandos' (geralmente em configurações / 50terminal.conf)."

#: gateone/applications/terminal/app_terminal.py:1030
#, python-format
msgid ""
"You are missing a 'default_command' in your terminal settings (usually "
"50terminal.conf in %s)"
msgstr "Está faltando um "default_command 'em suas configurações de terminais (normalmente 50terminal.conf em %s )"

#: gateone/applications/terminal/app_terminal.py:1042
#, python-format
msgid "%s: Attempted to execute invalid command (%s)."
msgstr "%s : Tentativa de executar o comando inválido ( %s )."

#: gateone/applications/terminal/app_terminal.py:1044
#, python-format
msgid "Terminal: Invalid command: %s"
msgstr "Terminal: Comando inválido: %s"

#: gateone/applications/terminal/app_terminal.py:1122
#, python-format
msgid "new_terminal cmd: %s"
msgstr "new_terminal cmd: %s"

#: gateone/applications/terminal/app_terminal.py:1186
msgid "WARNING: Logging is set to DEBUG.  All keystrokes will be logged!"
msgstr "AVISO: O registro é definido para depuração. Todas as teclas serão registradas!"

#: gateone/applications/terminal/app_terminal.py:1218
msgid ""
"Invalid encoding.  For a list of valid encodings see:<br><a "
"href='http://docs.python.org/2/library/codecs.html#standard-encodings' "
"target='new'>Standard Encodings</a>"
msgstr "Codificação inválido. Para obter uma lista de codificações válidas ver: <br> <a href='http://docs.python.org/2/library/codecs.html#standard-encodings' target='new'> Padrão Encodings </a>"

#: gateone/applications/terminal/app_terminal.py:1251
#, python-format
msgid "Invalid keyboard mode.  Must be one of: %s, "
msgstr "Modo de teclado inválido. Deve ser um dos seguintes: %s , "

#: gateone/applications/terminal/app_terminal.py:1273
msgid "Error: Terminal {term} does not exist."
msgstr "Erro: o Terminal {termo} não existe."

#: gateone/applications/terminal/app_terminal.py:1312
msgid "Error: Terminal {term} does not exist at the current location ({location})"
msgstr "Erro: o Terminal {termo} não existe no local atual ({local})"

#: gateone/applications/terminal/app_terminal.py:1363
#, python-format
msgid "Incoming terminal from location: %s"
msgstr "Terminal de entrada do local: %s"

#: gateone/applications/terminal/app_terminal.py:1602
#, python-format
msgid "WebSocket closed (%s)"
msgstr "WebSocket fechada ( %s )"

#: gateone/applications/terminal/app_terminal.py:1656
#, python-format
msgid "KeyError in refresh_screen: %s"
msgstr "KeyError em refresh_screen: %s"

#: gateone/applications/terminal/app_terminal.py:1664
#, python-format
msgid "Invalid terminal number given to full_refresh(): %s"
msgstr "Número do terminal inválido dado a full_refresh (): %s"

#: gateone/applications/terminal/app_terminal.py:1766
#, python-format
msgid "Got exception trying to write_chars() to terminal %sterm"
msgstr "Tem exceção tentando write_chars () ao terminal %s prazo"

#: gateone/applications/terminal/app_terminal.py:1808
msgid "Got exception trying to execute plugin's optional ESC sequence handler..."
msgstr "Tem exceção tentando executar manipulador seqüência opcional ESC do plugin ..."

#: gateone/applications/terminal/app_terminal.py:1824
#, python-format
msgid "Could not load bell: %s"
msgstr "Não foi possível carregar sino: %s"

#: gateone/applications/terminal/app_terminal.py:1861
#: gateone/core/server.py:2534
msgid "send_css is false; will not send JavaScript."
msgstr "send_css é falso; não enviará JavaScript."

#: gateone/applications/terminal/app_terminal.py:2041
msgid "{upn} updated sharing permissions on terminal {term} ({title}))"
msgstr "{} Upn permissões de compartilhamento atualizados no Terminal {termo} ({title}))"

#: gateone/applications/terminal/app_terminal.py:2170
#, python-format
msgid "Share ID '%s' is already in use"
msgstr "Compartilhar ID ' %s 'já está em uso"

#: gateone/applications/terminal/app_terminal.py:2183
msgid "{upn} changed share ID of terminal {term} from '{old}'' to '{new}'"
msgstr "{} Upn mudou share ID do terminal de {} termo de '{idade}' 'para' {novo} '"

#: gateone/applications/terminal/app_terminal.py:2203
msgid "Error: Invalid share ID."
msgstr "Erro: ID partes inválido."

#: gateone/applications/terminal/app_terminal.py:2241
msgid "No terminal associated with the given share_id."
msgstr "N associado com o terminal de share_id dada."

#: gateone/applications/terminal/app_terminal.py:2352
msgid "Invalid share_id."
msgstr "Share_id inválido."

#: gateone/applications/terminal/app_terminal.py:2362
msgid "Requested shared terminal does not exist."
msgstr "Terminais compartilhados solicitado não existe."

#: gateone/applications/terminal/app_terminal.py:2367
msgid "You are not authorized to view this terminal"
msgstr "Você não está autorizado a ver este terminal"

#: gateone/applications/terminal/app_terminal.py:2371
msgid "Invalid password."
msgstr "Senha inválida."

#: gateone/applications/terminal/app_terminal.py:2440
msgid "{upn} connected to terminal shared by {owner}"
msgstr "{} Upn ligado ao terminal compartilhado por {} proprietário"

#: gateone/applications/terminal/app_terminal.py:2448
#, python-format
msgid "%s (%s) is now viewing terminal %s"
msgstr "%s ( %s ) está vendo agora terminais %s"

#: gateone/applications/terminal/app_terminal.py:2709
#: gateone/core/configuration.py:890
msgid "// This is Gate One's Terminal application settings file.\n"
msgstr "// Este é o arquivo de configurações do aplicativo Terminal do Gate One. \ N"

#: gateone/applications/terminal/app_terminal.py:2725
msgid "dtach command not found.  dtach support has been disabled."
msgstr "dtach comando não encontrado. dtach apoio foi desativado."

#: gateone/applications/terminal/app_terminal.py:2730
msgid ""
"The default path to known_hosts has been changed.  Please update your "
"settings to use '/.ssh/known_hosts' instead of '/ssh/known_hosts'.  "
"Applying a termporary fix..."
msgstr "O caminho padrão para known_hosts foi alterado. Por favor, atualize suas configurações para usar '/.ssh/known_hosts' em vez de '/ ssh / known_hosts'. Aplicando uma correção termporary ..."

#: gateone/applications/terminal/app_terminal.py:2793
msgid "View terminal session logs."
msgstr "Exibir logs de sessão de terminal."

#: gateone/applications/terminal/policy.py:72
#, python-format
msgid ""
"%s denied opening new terminal.  The 'max_terms' policy limit (%s) has "
"been reached for this user."
msgstr "%s negou abrir novo terminal. O limite da apólice 'max_terms' ( %s ) foi alcançado para este usuário."

#: gateone/applications/terminal/policy.py:78
#, python-format
msgid "Server policy dictates that you may only open %s terminal(s) "
msgstr "Política Servidor dita que você só pode abrir %s do terminal (s) "

#: gateone/applications/terminal/policy.py:119
msgid ""
"{upn} denied executing {function_name} by policy (not owner of terminal "
"or does not have write access)."
msgstr "{} Upn negado execução {} function_name pela política (não proprietário de terminal ou não tem acesso de gravação)."

#: gateone/applications/terminal/policy.py:167
#, python-format
msgid "%s denied sharing terminal by policy.upn"
msgstr "%s negou compartilhando terminal policy.upn"

#: gateone/applications/terminal/policy.py:177
msgid "You do not have permission to write to this terminal."
msgstr "Você não tem permissão para escrever a este terminal."

#: gateone/applications/terminal/term_utils.py:75
msgid "Error decoding {0}.  File will be removed."
msgstr "Descodificação de erro {0} . O arquivo será removido."

#: gateone/applications/terminal/plugins/html/html.py:63
msgid "Raw HTML"
msgstr "Raw HTML"

#: gateone/applications/terminal/plugins/html/html.py:109
#, python-format
msgid "HTML Plugin: Sorry but the '%s' tag is not allowed."
msgstr "HTML Plugin: Desculpe, mas o ' %s 'tag não é permitido."

#: gateone/applications/terminal/plugins/html/html.py:117
msgid "HTML Plugin: Sorry but using 'javascript:' is not allowed."
msgstr "HTML Plugin: Desculpe, mas usando 'javascript:' não é permitido."

#: gateone/applications/terminal/plugins/html/html.py:124
msgid "HTML Plugin: Sorry but using JavaScript events is not allowed."
msgstr "HTML Plugin: Desculpe, mas o uso de eventos de JavaScript não é permitida."

#: gateone/applications/terminal/plugins/html/html.py:132
msgid "HTML Plugin: Sorry but using 'FSCommand' is not allowed."
msgstr "Plugin HTML: Desculpe, mas usando 'FSCommand' não é permitido."

#: gateone/applications/terminal/plugins/html/html.py:139
msgid "HTML Plugin: Sorry but using 'seekSegmentTime' is not allowed."
msgstr "Plugin HTML: Desculpe, mas usando 'seekSegmentTime' não é permitido."

#: gateone/applications/terminal/plugins/html/html.py:147
msgid "HTML Plugin: Sorry but using 'vbscript:' is not allowed."
msgstr "HTML Plugin: Desculpe, mas usando 'VBScript:' não é permitido."

#: gateone/applications/terminal/plugins/logging/logging_plugin.py:113
msgid ""
"NOTE: User session logging is disabled.  To enable it, set "
"'session_logging = True' in your server.conf."
msgstr "NOTA: registro de sessão do usuário está desativada. Para habilitá-lo, definir 'session_logging = True "em seu server.conf."

#: gateone/applications/terminal/plugins/logging/logging_plugin.py:121
msgid "NOTE: Your access to the log viewer has been restricted."
msgstr "NOTA: O acesso ao visualizador de log foi restringido."

#: gateone/applications/terminal/plugins/logging/logging_plugin.py:323
#: gateone/applications/terminal/plugins/logging/logging_plugin.py:456
#: gateone/applications/terminal/plugins/logging/logging_plugin.py:575
msgid "ERROR: Log not found"
msgstr "ERRO: Não Login encontrado"

#: gateone/applications/terminal/plugins/ssh/ssh.py:129
#, python-format
msgid "Renaming %s's 'ssh' directory to '.ssh'."
msgstr "Mudar o nome de %s 'do diretório para' ssh ssh 's'."

#: gateone/applications/terminal/plugins/ssh/ssh.py:133
#, python-format
msgid ""
"Both an 'ssh' and '.ssh' directory exist for user %s.  Using the .ssh "
"directory."
msgstr "Tanto um 'ssh' e diretório '.ssh' existe para o usuário %s . Usando o diretório ssh."

#: gateone/applications/terminal/plugins/ssh/ssh.py:159
#: gateone/applications/terminal/plugins/ssh/ssh.py:168
msgid "SSH Plugin: Unable to open slave sub-channel."
msgstr "SSH Plugin: Não é possível abrir sub-canal escravo."

#: gateone/applications/terminal/plugins/ssh/ssh.py:264
msgid "SSH sub-channel closed due to inactivity."
msgstr "Sub-canal SSH fechado devido à inatividade."

#: gateone/applications/terminal/plugins/ssh/ssh.py:276
#, python-format
msgid ""
"%s: Got an error trying to capture output inside of execute_command() "
"running: %s"
msgstr "%s : Tem um erro ao tentar capturar a saída dentro de execute_command () execução: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:285
msgid "Error: Timeout exceeded or command failed to execute."
msgstr "Erro: Tempo limite excedido ou falha de comando para executar."

#: gateone/applications/terminal/plugins/ssh/ssh.py:313
#, python-format
msgid "%s: Got an error trying to open sub-channel on term %s..."
msgstr "%s : Tem um erro ao tentar abrir sub-canal no termo %s ..."

#: gateone/applications/terminal/plugins/ssh/ssh.py:476
#, python-format
msgid "SSH Plugin Error: Invalid name given, %s"
msgstr "SSH Plugin de erro: Nome inválido dado, %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:495
#, python-format
msgid "SSH Plugin Error: Public key not found at %s"
msgstr "SSH Plugin Erro: chave pública não encontrado em %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:524
msgid "Error:  You must supply a 'host'."
msgstr "Erro: Você deve fornecer um 'host'."

#: gateone/applications/terminal/plugins/ssh/ssh.py:553
#, python-format
msgid "Error: Could not determine the fingerprint of %s:%s... '%s'"
msgstr "Erro: Não foi possível determinar a impressão digital de %s : %s ... ' %s '"

#: gateone/applications/terminal/plugins/ssh/ssh.py:617
msgid "Keypair generation failed."
msgstr "Geração de par de chaves falhou."

#: gateone/applications/terminal/plugins/ssh/ssh.py:623
#, python-format
msgid "There was a problem generating SSH keys: %s"
msgstr "Houve um problema gerando chaves SSH: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:641
msgid "Keypair generation complete"
msgstr "Geração de par de chaves completo"

#: gateone/applications/terminal/plugins/ssh/ssh.py:772
#, python-format
msgid "Error generating public key from private key at %s"
msgstr "Erro ao gerar a chave pública de chave privada em %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:841
msgid "You must specify a valid *name*."
msgstr "Você deve especificar um nome * válido *."

#: gateone/applications/terminal/plugins/ssh/ssh.py:848
msgid "No files were given to save!"
msgstr "Nenhum arquivo foi dada para salvar!"

#: gateone/applications/terminal/plugins/ssh/ssh.py:869
msgid "ERROR: Private key is not valid."
msgstr "ERRO: A chave privada não é válido."

#: gateone/applications/terminal/plugins/ssh/ssh.py:880
msgid "Got public key, cancelling public key generation timer."
msgstr "Recebeu a chave pública, o cancelamento temporizador geração de chave pública."

#: gateone/applications/terminal/plugins/ssh/ssh.py:891
msgid ""
"Only received a private key.  Setting timeout to generate the public key "
"if not received within 3 seconds."
msgstr "Só recebeu uma chave privada. Definir o tempo limite para gerar a chave pública se não for recebido dentro de 3 segundos."

#: gateone/applications/terminal/plugins/ssh/ssh.py:909
#, python-format
msgid "Error saving keys: %s"
msgstr "Chaves de poupança de erro: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:936
#, python-format
msgid "Error deleting keypair: %s"
msgstr "Erro ao excluir par de chaves: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:1029
#, python-format
msgid "Error getting identities: %s"
msgstr "Erro ao obter identidades: %s"

#: gateone/applications/terminal/plugins/ssh/ssh.py:1119
#, python-format
msgid "Error creating user's ssh directory: %s\n"
msgstr "Erro ao criar diretório ssh do usuário: %s \ n"

#: gateone/applications/terminal/plugins/ssh/ssh.py:1145
#, python-format
msgid ""
"Could not set %s as executable.  You will need to 'chmod a+x' that script"
" manually."
msgstr "Não foi possível definir %s como executável. Você vai precisar de "chmod a + x 'que script manualmente."

#: gateone/applications/terminal/plugins/ssh/ssh.py:1148
msgid ""
"Error loading SSH plugin:  The ssh_connect.py script is not executable.  "
"See the logs for more details."
msgstr "Erro ao carregar SSH plugin: O script ssh_connect.py não é executável. Veja os logs para obter mais detalhes."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:263
#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:486
msgid "The port must be an integer < 65535"
msgstr "A porta deve ser um número inteiro <65535"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:337
msgid "The following SSH identities are being used for this connection:"
msgstr "As seguintes identidades SSH estão sendo utilizados para esta ligação:"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:345
#, python-format
msgid "\t[1m%s[0m"
msgstr "\ T [1m %s [0m"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:390
#, python-format
msgid ""
"]_;notice|Existing ssh session detected for ssh://%s@%s:%s; utilizing "
"existing tunnel."
msgstr "] _; Notar | Existente sessão ssh detectado por ssh: // %s @ %s : %s ; utilizando túnel existente."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:507
#, python-format
msgid "Error: Could not find telnet binary in path %r"
msgstr "Erro: Não foi possível encontrar o binário telnet no caminho% r"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:645
msgid ""
"Path to the ssh command.  Default: 'ssh' (which usually means "
"/usr/bin/ssh)."
msgstr "Caminho para o comando ssh. Padrão: 'ssh' (o que geralmente significa / usr / bin / ssh)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:660
msgid "[Press Enter to close this terminal]"
msgstr "[Pressione Enter para fechar este terminal]"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:665
msgid ""
"Any additional arguments that should be passed to the ssh command.  It is"
" recommended to wrap these in quotes."
msgstr "Quaisquer argumentos adicionais que devem ser passadas para o comando ssh. Recomenda-se a envolver estes em aspas."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:672
msgid ""
"Path to the control socket for connection sharing (see master mode and "
"'man ssh')."
msgstr "Caminho para a tomada de controle para compartilhamento de conexão (ver modo mestre e "man ssh ')."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:680
msgid ""
"Enable the use of SSHFP in verifying host keys. See:  "
"http://en.wikipedia.org/wiki/SSHFP#SSHFP"
msgstr "Habilite o uso de SSHFP em verificar chaves de host. Veja: http://en.wikipedia.org/wiki/SSHFP#SSHFP"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:687
msgid "Enable the VisualHostKey (randomart hash host key) option when connecting."
msgstr "Habilite o VisualHostKey (chave de host de hash randomart) opção quando ligar."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:694
msgid "Display the logo image inline in the terminal."
msgstr "Mostrar a imagem do logotipo em linha no terminal."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:699
msgid "Provide the logo path (implies --logo)."
msgstr "Forneça o caminho do logotipo (implica --Logotipo)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:704
msgid ""
"The default host that will be used for outbound connections if no "
"hostname is provided.  Default: localhost"
msgstr "A máquina padrão que será usado para conexões de saída se nenhum nome de host é fornecido. Padrão: localhost"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:711
msgid ""
"The default port that will be used for outbound connections if no port is"
" provided.  Default: 22"
msgstr "A porta padrão que será usado para conexões de saída, se nenhuma porta for fornecido. Padrão: 22"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:718
msgid ""
"Skip asking for host information (hostname and port) and ask for "
"credentials only (you probably want to use --default_host and "
"--default_port as well)."
msgstr "Ir pedindo informações do host (hostname e porta) e pedir credenciais só (você provavelmente vai querer usar --default_host e --default_port também)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:785
msgid "Error:  You must enter a valid hostname or IP address."
msgstr "Erro: Você deve digitar um nome de host ou endereço IP válidos."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:787
msgid "Error:  You must enter a valid port (1-65535)."
msgstr "Erro: Você deve digitar uma porta válida (1-65535)."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:789
msgid "Error:  You must enter a valid username."
msgstr "Erro: Você deve digitar um nome de usuário válido."

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:801
#, python-format
msgid ""
"[Press Shift-F1 for help]\n"
"\n"
"Host/IP or ssh:// URL%s: "
msgstr "[Pressione Shift-F1 para ajuda] \ n \ nHost / IP ou ssh: // URL %s : "

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:849
#, python-format
msgid "%s: "
msgstr "%s "

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:874
#, python-format
msgid "Connecting to ssh://%s@%s:%s"
msgstr "Conectando-se a ssh: // %s @ %s : %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:894
#, python-format
msgid "Connecting to telnet://%s@%s:%s"
msgstr "Conectando-se a telnet: // %s @ %s : %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:898
#, python-format
msgid "Connecting to telnet://%s:%s"
msgstr "Conectando-se a telnet: // %s : %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:903
#, python-format
msgid "Unknown protocol \"%s\""
msgstr "Protocolo desconhecido \ " %s \ ""

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:907
#, python-format
msgid "Got Exception: %s"
msgstr "Tem Exceção: %s"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:912
msgid "[Press any key to close this terminal]"
msgstr "[Pressione qualquer tecla para fechar este terminal]"

#: gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py:916
msgid ""
"\n"
"User requested exit.  Quitting..."
msgstr "\ Nuser solicitado saída. Parar de ..."

#: gateone/applications/x11/app_x11.py:90
msgid ""
"If provided, will use the specified xorg.conf file when spawning "
"instances of Xorg."
msgstr "Se fornecido, usará o arquivo xorg.conf especificado quando desova casos de Xorg."

#: gateone/applications/x11/app_x11.py:328
#, python-format
msgid "Starting screenshot_process() (PID: %s)"
msgstr "Screenshot_process inicial () (PID: %s )"

#: gateone/applications/x11/app_x11.py:343
#, python-format
msgid "Terminating screenshot_process() (PID: %s)"
msgstr "Finalizando screenshot_process () (PID: %s )"

#: gateone/applications/x11/app_x11.py:420
msgid "Run X11 applications."
msgstr "Executar aplicativos X11."

#: gateone/applications/x11/app_x11.py:528
#, python-format
msgid "Active X11 Plugins: %s, "
msgstr "Ativa X11 Plugins: %s , "

#: gateone/applications/x11/app_x11.py:1238
msgid ""
"Images are taking too long to process.  Forcing output settings to "
"safe/low overhead defaults."
msgstr "Imagens estão demorando muito para processar. Forçando as configurações de saída para baixo padrões seguros / aéreos."

#: gateone/applications/x11/app_x11.py:1253
msgid "Resuming original output settings."
msgstr "Retomando as definições de saída originais."

#: gateone/applications/x11/app_x11.py:1299
msgid "Client bandiwdth: {0}/sec"
msgstr "Bandiwdth Cliente: {0} / sec"

#: gateone/applications/x11/app_x11.py:1712
#, python-format
msgid "Could not connect to the X11 server (display %s)"
msgstr "Não foi possível conectar ao servidor X11 (visualização %s )"

#: gateone/applications/x11/app_x11.py:1873
#, python-format
msgid "x11_command: %s"
msgstr "x11_command: %s"

#: gateone/applications/x11/app_x11.py:2147
#, python-format
msgid "Invalid display number given to full_refresh(): %s"
msgstr "Número de exibição inválido dado a full_refresh (): %s"

#: gateone/applications/x11/app_x11.py:2310
msgid ""
"Error: Too too long waiting for the X11 display to start up.  Something "
"is wrong with the server."
msgstr "Erro: Too muito tempo de espera para a exibição X11 para o arranque. Algo está errado com o servidor."

#: gateone/applications/x11/app_x11.py:2323
#, python-format
msgid ""
"Error: The given display (%s) does not exist or you have not been granted"
" access to it."
msgstr "Erro: A exibição dada ( %s ) não existe ou você não tem acesso a ela."

#: gateone/applications/x11/app_x11.py:2336
#, python-format
msgid "Application not configured: %s"
msgstr "O aplicativo não configurado: %s"

#: gateone/applications/x11/app_x11.py:2441
msgid "// This is Gate One's X11 application settings file.\n"
msgstr "// Este é o arquivo de configurações do aplicativo do Gate One X11. \ N"

#: gateone/applications/x11/app_x11.py:2453
#, python-format
msgid "%s not found.  Creating using template..."
msgstr "%s não encontrado. Criando usando o modelo ..."

#: gateone/applications/x11/app_x11.py:2459
#, python-format
msgid "%s created successfully."
msgstr "%s criado com sucesso."

#: gateone/applications/x11/app_x11.py:2461
#, python-format
msgid "Could not create xorg.conf (%s)"
msgstr "Não foi possível criar xorg.conf ( %s )"

#: gateone/applications/x11/app_x11.py:2525
msgid "Path to docker command (if not just 'docker' in $PATH)."
msgstr "Caminho comando para janela de encaixe (se não apenas "estivador" no $ PATH)."

#: gateone/applications/x11/app_x11.py:2531
msgid "Name of the docker image to create."
msgstr "Nome da imagem janela de encaixe para criar."

#: gateone/applications/x11/app_x11.py:2537
msgid "Name of the command (will show up in the application chooser)."
msgstr "Nome do comando (vai aparecer no seletor de aplicação)."

#: gateone/applications/x11/app_x11.py:2543
msgid "Description of the command (help text for users)."
msgstr "Descrição do comando (texto de ajuda para usuários)."

#: gateone/applications/x11/app_x11.py:2549
msgid ""
"Packages to install (if the command doesn't match the package name).  "
"Additional packages may also be given to install alongside the given "
"command inside the Docker container.  They will be installed via 'apt-get"
" install <packages>"
msgstr "Pacotes para instalar (se o comando não coincide com o nome do pacote). Pacotes adicionais também podem ser dadas para instalar junto com o comando dado no interior do recipiente Docker. Eles serão instalados via 'apt-get install <pacotes>"

#: gateone/applications/x11/app_x11.py:2557
msgid "ERROR: You must specify at least one application to install and configure."
msgstr "Erro: Você deve especificar pelo menos um aplicativo para instalar e configurar."

#: gateone/applications/x11/app_x11.py:2601
msgid "Adds X11 applications to Gate One."
msgstr "Adiciona aplicativos X11 para Gate One."

#: gateone/applications/x11/x11.py:1310
msgid "X11Display.resize(): Values must be given as integers."
msgstr "X11Display.resize (): Os valores devem ser dados como números inteiros."

#: gateone/applications/x11/x11.py:1572
#, python-format
msgid "Could not find keysym for key: %s"
msgstr "Não foi possível encontrar keysym chave: %s"

#: gateone/applications/x11/x11.py:1573
msgid ""
"Please report what key you pressed and the above information in a ticket "
"here: https://github.com/liftoff/GateOne/issues (we'll make it work)"
msgstr "Por favor, reporte o que tecla pressionada e as informações acima em um bilhete aqui: https://github.com/liftoff/GateOne/issues (vamos fazer o trabalho)"

#: gateone/applications/x11/x11.py:1728 gateone/applications/x11/x11.py:1784
msgid "Could not load dbus module.  Screensaver inhibiting probably won't work."
msgstr "Não foi possível carregar módulo dbus. Inibidor Screensaver provavelmente não vai funcionar."

#: gateone/applications/x11/x11.py:1776
msgid "Cannot re-enable a screensaver that was not disabled via this mechanism."
msgstr "Não é possível reativar um protetor de tela que não foi desativado através deste mecanismo."

#: gateone/applications/x11/x11.py:2118
#, python-format
msgid ""
"frame_extents() takes a tuple (or list) of integers in the form of: "
"(left, right, top, bottom).  %s is not valid"
msgstr "frame_extents () recebe uma tupla (ou lista) de inteiros na forma de: (esquerda, direita, superior e inferior). %s não é válido"

#: gateone/asynchronous/asynchronous.py:138
#, python-format
msgid "Exception in Future: %s (id: %s)"
msgstr "Exceção no futuro: %s (ID: %s )"

#: gateone/asynchronous/asynchronous.py:223
#, python-format
msgid "Shutting down %s"
msgstr "Desligando %s"

#: gateone/asynchronous/asynchronous.py:429
#, python-format
msgid "Starting the ThreadedRunner executor with %s worker threads."
msgstr "Iniciando o executor ThreadedRunner com %s segmentos de trabalho."

#: gateone/asynchronous/asynchronous.py:480
#, python-format
msgid "Starting the MultiprocessRunner executor with %s worker processes."
msgstr "Iniciando o executor MultiprocessRunner com %s processos de trabalho."

#: gateone/asynchronous/asynchronous.py:513
msgid "Shutting down the MultiprocessRunner executor."
msgstr "Desligar o executor MultiprocessRunner."

#: gateone/auth/authentication.py:158 gateone/auth/authentication.py:250
#: gateone/core/server.py:1987
#, python-format
msgid "Creating user directory: %s"
msgstr "Criando diretório de usuário: %s"

#: gateone/auth/authentication.py:162
msgid ""
"You're trying to use non-ASCII user information on a system that has the "
"locale set to ASCII (or similar).  Please changeyour system's locale to "
"something that supports Unicode characters. "
msgstr "Você está tentando usar as informações do usuário não-ASCII em um sistema que tem o local definido para ASCII (ou similar). Por favor changeyour locale do sistema para algo que suporta caracteres Unicode. "

#: gateone/auth/authentication.py:365
msgid "Google auth failed"
msgstr "Google auth falhou"

#: gateone/auth/authentication.py:508
msgid "Kerberos auth failed"
msgstr "Auth Kerberos falhou"

#: gateone/auth/authentication.py:509
#, python-format
msgid "KerberosAuthHandler user: %s"
msgstr "KerberosAuthHandler usuário: %s"

#: gateone/auth/authentication.py:564
msgid "PAM auth failed"
msgstr "PAM de autenticação falhou"

#: gateone/auth/authentication.py:568
#, python-format
msgid "PAMAuthHandler user: %s"
msgstr "PAMAuthHandler usuário: %s"

#: gateone/auth/authentication.py:590
msgid "CAS Server URL"
msgstr "CAS URL do servidor"

#: gateone/auth/authentication.py:693
msgid "CAS authentication failed"
msgstr "Autenticação CAS falhou"

#: gateone/auth/authorization.py:116
#, python-format
msgid "{\"ip_address\": \"%s\"} %s -> %s failed requirement: %s"
msgstr "{\ "Endereco_ip \": \ " %s \ "} %s -> %s exigência falhou: %s"

#: gateone/auth/authorization.py:121
#, python-format
msgid "{\"ip_address\": \"%s\"} unknown user -> %s failed requirement: %s"
msgstr "{\ "Endereco_ip \": \ " %s \ "} usuário desconhecido -> %s exigência falhou: %s"

#: gateone/auth/authorization.py:124
#, python-format
msgid "ERROR: %s"
msgstr "ERRO: %s"

#: gateone/auth/authorization.py:148
msgid "Only valid users may access this function"
msgstr "Somente usuários podem acessar esta função"

#: gateone/auth/authorization.py:169
msgid "You are not authorized to perform this action"
msgstr "Você não está autorizado a realizar esta ação"

#: gateone/auth/authorization.py:228
msgid "Your ability to perform this action has been restricted"
msgstr "Sua capacidade de executar esta ação foi restringida"

#: gateone/auth/sso.py:132 gateone/auth/sso.py:133
msgid "Kerberos/GSSAPI Single Sign-On"
msgstr "Kerberos / GSSAPI Single Sign-On"

#: gateone/auth/sso.py:164 gateone/auth/sso.py:174
msgid "Kerberos Init failed"
msgstr "Kerberos Init falhou"

#: gateone/auth/sso.py:173
#, python-format
msgid "Kerberos Error: %s"
msgstr "Erro Kerberos: %s"

#: gateone/auth/sso.py:214
msgid "Headers have already been written"
msgstr "Cabeçalhos já foram escritos"

#: gateone/core/configuration.py:187
msgid ""
"GateOne supports many different CLI 'commands' which can be used to "
"invoke special functionality provided by plugins and applications (and "
"application's plugins).  Each command can have it's own options and most "
"will have a --help function of their own."
msgstr "GateOne suporta muitos 'comandos' CLI diferentes que podem ser usados ​​para invocar a funcionalidade especial fornecido pela plugins e aplicativos (e plugins do aplicativo). Cada comando pode ter seu próprio opções ea maioria vai ter uma função --help própria."

#: gateone/core/configuration.py:296
msgid "Display version information."
msgstr "Apresenta versão."

#: gateone/core/configuration.py:301
msgid "DEPRECATED.  Use --settings_dir."
msgstr "Depreciado. Use --settings_dir."

#: gateone/core/configuration.py:307
msgid "Path to the settings directory."
msgstr "Caminho para o diretório de configurações."

#: gateone/core/configuration.py:314
msgid ""
"Path where Gate One should store temporary global files (e.g. rendered "
"templates, CSS, JS, etc)."
msgstr "Caminho onde Gate One deve armazenar os arquivos temporários globais (por exemplo, modelos prestados, CSS, JS, etc)."

#: gateone/core/configuration.py:323
msgid "Enable debugging features such as auto-restarting when files are modified."
msgstr "Ativar a depuração recursos como auto-reiniciar quando os arquivos são modificados."

#: gateone/core/configuration.py:329
msgid "Use the given 45-character string for cookie encryption."
msgstr "Use a seqüência de 45 caracteres para criptografia de dados cookie."

#: gateone/core/configuration.py:335
msgid "DEPRECATED: Use the 'commands' option in the terminal settings."
msgstr "Reprovado: Utilize a opção 'comandos' nas configurações do terminal."

#: gateone/core/configuration.py:342
msgid ""
"Run on the given address.  Default is all addresses (IPv6 included).  "
"Multiple address can be specified using a semicolon as a separator (e.g. "
"'127.0.0.1;::1;10.1.1.100')."
msgstr "Correr no endereço dado. O padrão é todos os endereços IPv6 (incluído). Endereço múltipla pode ser especificado utilizando um ponto e vírgula como separador (por exemplo, "127.0.0.1; :: 1; 10.1.1.100)."

#: gateone/core/configuration.py:349
msgid "Run on the given port."
msgstr "Correr na porta dada."

#: gateone/core/configuration.py:355
msgid "Enable Unix socket support."
msgstr "Ative o suporte ao socket Unix."

#: gateone/core/configuration.py:361
msgid "Path to the Unix socket (if --enable_unix_socket=True)."
msgstr "Caminho para o socket Unix (se --enable_unix_socket = True)."

#: gateone/core/configuration.py:368
msgid "If enabled Gate One will run without SSL (generally not a good idea)."
msgstr "Se ativado Gate One será executado sem SSL (geralmente não é uma boa idéia)."

#: gateone/core/configuration.py:375
msgid "Path to the SSL certificate.  Will be auto-generated if not found."
msgstr "Caminho para o certificado SSL. Será gerada automaticamente se não for encontrado."

#: gateone/core/configuration.py:384
msgid "Path to the SSL keyfile.  Will be auto-generated if none is provided."
msgstr "Caminho para o arquivo de chave SSL. Será gerada automaticamente se nenhuma for fornecido."

#: gateone/core/configuration.py:392
msgid ""
"Path to a file containing any number of concatenated CA certificates in "
"PEM format.  They will be used to authenticate clients if the 'ssl_auth' "
"option is set to 'optional' or 'required'."
msgstr "Caminho para um arquivo contendo qualquer número de certificados CA concatenados em formato PEM. Eles serão usados ​​para autenticar os clientes se a opção 'ssl_auth' é definida como 'opcional' ou 'necessário'."

#: gateone/core/configuration.py:402
msgid ""
"Enable the use of client SSL (X.509) certificates as a secondary "
"authentication factor (the configured 'auth' type will come after SSL "
"auth).  May be one of 'none', 'optional', or 'required'.  NOTE: Only "
"works if the 'ca_certs' option is configured."
msgstr "Habilite o uso de SSL cliente (X.509) certificados como um fator de autenticação secundário (o 'auth' tipo configurado virá depois auth SSL). Pode ser um dos 'none', 'opcional', ou 'necessário'. NOTA: Só funciona se a opção 'ca_certs' está configurado."

#: gateone/core/configuration.py:413
msgid "Path to the location where user files will be stored."
msgstr "Caminho para o local onde os arquivos do usuário será armazenado."

#: gateone/core/configuration.py:420
msgid ""
"Maximum length of time to keep any given user log before it is "
"automatically removed."
msgstr "O comprimento máximo de tempo para manter qualquer registro de usuário dada antes de ser automaticamente removido."

#: gateone/core/configuration.py:429
msgid "Path to the location where session information will be stored."
msgstr "Caminho para o local onde as informações da sessão será armazenado."

#: gateone/core/configuration.py:439
#, python-format
msgid ""
"Syslog facility to use when logging to syslog (if syslog_session_logging "
"is enabled).  Must be one of: %s., "
msgstr "Syslog para usar ao fazer login no syslog (se syslog_session_logging está habilitado). Deve ser um dos seguintes: %s ., "

#: gateone/core/configuration.py:446
msgid ""
"Amount of time that a session is allowed to idle before it is killed.  "
"Accepts <num>X where X could be one of s, m, h, or d for seconds, "
"minutes, hours, and days.  Set to '0' to disable the ability to resume "
"sessions."
msgstr "Quantidade de tempo que uma sessão é permitida a ficar ociosa antes de ser morto. Aceita <num> X, onde X pode ser um dos s, m, h, ou d para segundos, minutos, horas e dias. Defina como "0" para desativar a capacidade de recuperar sessões."

#: gateone/core/configuration.py:456
msgid ""
"Generate a new API key that an external application can use to embed Gate"
" One."
msgstr "Gerar uma nova chave de API que uma aplicação externa pode usar para incorporar Gate One."

#: gateone/core/configuration.py:463
#, python-format
msgid "Authentication method to use.  Valid options are: %s"
msgstr "Método de autenticação para usar. As opções válidas são: %s"

#: gateone/core/configuration.py:474
msgid "How long before an API authentication object becomes invalid."
msgstr "Quanto tempo antes de um objeto de autenticação API torna-se inválido."

#: gateone/core/configuration.py:482
msgid ""
"Kerberos REALM (aka DOMAIN) to use when authenticating clients.  Only "
"relevant if Kerberos authentication is enabled."
msgstr "Domínio Kerberos (aka domínio) para usar ao autenticar clientes. Só é relevante se a autenticação Kerberos está ativado."

#: gateone/core/configuration.py:490
msgid ""
"Kerberos service (aka application) to use.  Only relevant if Kerberos "
"authentication is enabled."
msgstr "Serviço Kerberos (aka aplicativo) para usar. Só é relevante se a autenticação Kerberos está ativado."

#: gateone/core/configuration.py:498
msgid ""
"Basic auth REALM to display when authenticating clients.  Default: "
"hostname.  Only relevant if PAM authentication is enabled."
msgstr "REINO autenticação básica para exibir ao autenticar clientes. Padrão: hostname. Só é relevante se a autenticação PAM está ativado."

#: gateone/core/configuration.py:509
msgid ""
"PAM service to use.  Defaults to 'login'. Only relevant if PAM "
"authentication is enabled."
msgstr "Serviço PAM para usar. O padrão é 'login'. Só é relevante se a autenticação PAM está ativado."

#: gateone/core/configuration.py:517
msgid ""
"When embedding Gate One this option is available to plugins, "
"applications, and templates so they know they're running in embedded mode"
" and can change behavior (if necessary)."
msgstr "Ao incorporar Gate One esta opção está disponível para plugins, aplicações e modelos para que eles sabem que estão em execução no modo integrado e pode mudar o comportamento (se necessário)."

#: gateone/core/configuration.py:529
#, python-format
msgid ""
"The locale (e.g. pt_PT) Gate One should use for translations.  If not "
"provided, will default to $LANG (which is '%s' in your current shell)."
msgstr "A localidade (ex pt_PT) Gate One deve usar para traduções. Se não for fornecido, será o padrão para $ LANG (que é ' %s 'em seu shell atual)."

#: gateone/core/configuration.py:535
msgid ""
"A JavaScript object (string) that will be used when running "
"GateOne.init() inside index.html.  Example: --js_init=\"{theme: "
"'white'}\" would result in GateOne.init({theme: 'white'})"
msgstr "Um objeto JavaScript (string) que será utilizado durante a execução GateOne.init () dentro index.html. Exemplo: --js_init = \ "{tema: 'branco'} \" resultaria em GateOne.init ({tema: 'branco'})"

#: gateone/core/configuration.py:545
msgid ""
"If enabled a separate listener will be started on port 80 that redirects "
"users to the configured port using HTTPS."
msgstr "Se ativado um ouvinte separado será iniciado na porta 80 que redireciona os usuários para a porta configurada usando HTTPS."

#: gateone/core/configuration.py:552
msgid ""
"An optional prefix to place before all Gate One URLs. e.g. '/gateone/'.  "
"Use this if Gate One will be running behind a reverse proxy where you "
"want it to be located at some sub-URL path."
msgstr "Um prefixo opcional para colocar diante de todos os Gate One URLs. por exemplo, '/ gateone /'. Use isto se Gate One estará correndo atrás de um proxy reverso onde você quer que ele seja localizado em algum caminho sub-URL."

#: gateone/core/configuration.py:562
msgid ""
"A semicolon-separated list of origins you wish to allow access to your "
"Gate One server over the WebSocket.  This value may contain "
"hostnames/FQDNs (e.g. foo;foo.bar;) and IP addresses.  This value must "
"contain all the hostnames/IPs that users will use to connect to Gate One."
"  Alternatively, '*' may be  specified to allow access from anywhere.  "
"NOTE: Using a '*' is only a good idea if you've configured Gate One to "
"use API authentication."
msgstr "Uma lista separada por vírgula de origens você deseja permitir o acesso à sua Um servidor Portão sobre o WebSocket. Este valor pode conter nomes de host / FQDN (por exemplo foo; foo.bar;) e endereços IP. Este valor deve conter todos os nomes de host / IPS que os usuários usam para conectar a Gate One. Alternativamente, '*' pode ser especificado para permitir o acesso de qualquer lugar. NOTA: A utilização de um '*' é apenas uma boa idéia se você tiver configurado Gate One para utilizar a autenticação API."

#: gateone/core/configuration.py:576
msgid "Define the path to the pid file."
msgstr "Defina o caminho para o arquivo pid."

#: gateone/core/configuration.py:583
msgid "Drop privileges and run Gate One as this user/uid."
msgstr "Solte privilégios e executar Gate One com este usuário / uid."

#: gateone/core/configuration.py:590
msgid "Drop privileges and run Gate One as this group/gid."
msgstr "Solte privilégios e executar Gate One como este grupo / gid."

#: gateone/core/configuration.py:597
msgid ""
"The 'key:secret,...' API key pairs you wish to use (only applies if using"
" API authentication)"
msgstr "A 'chave: segredo, ...' pares chave API que você deseja usar (só se aplica se estiver usando autenticação API)"

#: gateone/core/configuration.py:605
msgid ""
"Combines all of Gate One's JavaScript files into one big file and saves "
"it to the given path (e.g. ./gateone.py --combine_js=/tmp/gateone.js)"
msgstr "Combina todos os arquivos JavaScript do Gate One em um grande arquivo e salva-lo para o caminho dado (por exemplo ./gateone.py --combine_js = / tmp / gateone.js)"

#: gateone/core/configuration.py:615
msgid ""
"Combines all of Gate One's CSS Template files into one big file and saves"
" it to the given path (e.g. ./gateone.py --combine_css=/tmp/gateone.css)."
msgstr "Combina todos os arquivos de modelo CSS do Gate One em um grande arquivo e salvá-lo para o caminho determinado (por exemplo, ./gateone.py --combine_css = / tmp / gateone.css)."

#: gateone/core/configuration.py:625
msgid ""
"Use this setting in conjunction with --combine_css if the <div> where "
"Gate One lives is named something other than #gateone"
msgstr "Utilize esta definição em conjunto com --combine_css se o <div> onde Gate One vive é um nome diferente de #gateone"

#: gateone/core/configuration.py:634
msgid ""
"The number of processes to spawn use when using multiprocessing. Default "
"is: <number of cores> + 1.  Set to 0 to disable multiprocessing."
msgstr "O número de processos para gerar aquando da utilização de multiprocessamento. O padrão é: <número de núcleos> + 1 Set 0 para desabilitar multiprocessamento."

#: gateone/core/configuration.py:644
msgid ""
"Only configure Gate One (create SSL certs, conf.d, etc).  Do not start "
"any Gate One processes."
msgstr "Só configurar Gate One (criar certificados SSL, conf.d, etc). Não inicie qualquer Gate One processos."

#: gateone/core/configuration.py:704
msgid ""
"Gate One settings are incomplete.  A new <settings_dir>/10server.conf "
"will be generated."
msgstr "Gate One estão incompletas. Uma nova <settings_dir> /10server.conf será gerado."

#: gateone/core/configuration.py:712
msgid ""
"You have a 10server.conf but it is either invalid (syntax error) or "
"missing essential settings."
msgstr "Você tem um 10server.conf mas é inválido (erro de sintaxe) ou faltando ajustes essenciais."

#: gateone/core/configuration.py:818
#, python-format
msgid ""
"Old server.conf file found.  Converting to the new format as %s, %s, and "
"%s"
msgstr "Arquivo server.conf velho encontrado. Convertendo para o novo formato como %s , %s , e %s"

#: gateone/core/configuration.py:861 gateone/core/server.py:4269
msgid ""
"// This file contains the key and secret pairs used by Gate One's API "
"authentication method.\n"
msgstr "// Este arquivo contém a chave e pares secretas usadas pelo método de autenticação API do Gate One. \ N"

#: gateone/core/configuration.py:873
msgid "// This is Gate One's main settings file.\n"
msgstr "// Este é o arquivo de configurações principal do Gate One. \ N"

#: gateone/core/configuration.py:879
msgid "// This is Gate One's authentication settings file.\n"
msgstr "// Este é o arquivo de configurações de autenticação do Gate One. \ N"

#: gateone/core/configuration.py:973
#, python-format
msgid "%s does not exist"
msgstr "%s não existe"

#: gateone/core/configuration.py:1005
msgid " <-- Something went wrong right here (or right above it)"
msgstr " <- Algo deu errado aqui (ou à direita acima)"

#: gateone/core/configuration.py:1013
msgid ""
"Got an exception trying to display precisely where the problem was.  This"
" usually happens when you've used single quotes (') instead of double "
"quotes (\")."
msgstr "Tenho uma exceção tentando mostrar exatamente onde era o problema. Isso geralmente acontece quando você usou aspas simples (') em vez de aspas duplas (\ ")."

#: gateone/core/configuration.py:1321
#, python-format
msgid "Non-theme CSS has been combined and saved to: %s"
msgstr "Não tema CSS foi combinado e salvo: %s"

#: gateone/core/configuration.py:1337
#, python-format
msgid "The %s theme CSS has been combined and saved to: %s"
msgstr "O %s tema CSS foi combinado e salvo: %s"

#: gateone/core/server.py:493
#, python-format
msgid "Removing log due to age (>%s old): %s"
msgstr "Remoção de log devido à idade (> %s de idade): %s"

#: gateone/core/server.py:537
#, python-format
msgid "Removing old session files due to age (>%s old): %s"
msgstr "Removendo arquivos de sessão de idade devido à idade (> %s de idade): %s"

#: gateone/core/server.py:559
#, python-format
msgid "You do not have permission to send messages to %s."
msgstr "Você não tem permissão para enviar mensagens para %s ."

#: gateone/core/server.py:579
msgid "You do not have permission to broadcast messages."
msgstr "Você não tem permissão para transmitir mensagens."

#: gateone/core/server.py:590
msgid "You do not have permission to list connected users."
msgstr "Você não tem permissão para listar os usuários conectados."

#: gateone/core/server.py:632
msgid "Killing all sessions..."
msgstr "Matar todas as sessões ..."

#: gateone/core/server.py:677
msgid "All user sessions have terminated."
msgstr "Todas as sessões de usuário já estiver concluído."

#: gateone/core/server.py:693
msgid "{session} timeout."
msgstr "Tempo limite da sessão terminou"

#: gateone/core/server.py:701
msgid "Exception encountered in timeout_sessions(): {exception}"
msgstr "Exceção encontrado em timeout_sessions (): {} exceção"

#: gateone/core/server.py:725
#, python-format
msgid "Broadcasting %s to all users"
msgstr "Transmitindo %s para todos os usuários"

#: gateone/core/server.py:901
msgid "DownloadHandler: Could not determine use session"
msgstr "DownloadHandler: não foi possível determinar o uso da sessão"

#: gateone/core/server.py:1245
msgid "{path} has been removed.  Removing from file checker."
msgstr "{Caminho} foi removido. Remoção de verificador de arquivo."

#: gateone/core/server.py:1258
msgid ""
"Exception encountered trying to execute the file update function for "
"{path}..."
msgstr "Exceção encontrado ao tentar executar a função de atualização de arquivo para {caminho} ..."

#: gateone/core/server.py:1289
#, python-format
msgid "Settings have been modified.  Reloading from %s"
msgstr "As configurações foram modificadas. Recarregando a partir de %s"

#: gateone/core/server.py:1296
msgid "Settings have NOT been loaded."
msgstr "Definições não tiverem sido carregados."

#: gateone/core/server.py:1354
#, python-format
msgid "(Broadcast) %s"
msgstr "(Broadcast) %s"

#: gateone/core/server.py:1587
#, python-format
msgid "{\"ip_address\": \"%s\"} Access Denied (blacklisted)."
msgstr "{\ "Endereco_ip \": \ " %s \ "} Acesso negado (lista negra)."

#: gateone/core/server.py:1590
#, python-format
msgid "Your IP address (%s) has been blacklisted"
msgstr "O seu endereço de IP ( %s ) foi colocado na lista negra"

#: gateone/core/server.py:1602
#, python-format
msgid "WebSocket opened (%s %s) via origin %s."
msgstr "WebSocket aberta ( %s %s ) através de origem %s ."

#: gateone/core/server.py:1606
#, python-format
msgid "{\"ip_address\": \"%s\"} WebSocket opened (unknown user)."
msgstr "{\ "Endereco_ip \": \ " %s \ "} WebSocket aberto (usuário desconhecido)."

#: gateone/core/server.py:1617
#, python-format
msgid "{\"ip_address\": \"%s\"} Unauthenticated WebSocket attempt."
msgstr "{\ "Endereco_ip \": \ " %s \ "} tentativa WebSocket não autenticado."

#: gateone/core/server.py:1679
msgid "Message rejected due to invalid origin."
msgstr "Mensagem rejeitada devido a origem inválido."

#: gateone/core/server.py:1685
msgid "'Error: Message bust be a JSON dict.'"
msgstr "'Erro: Mensagem de busto ser um dicionário JSON."

#: gateone/core/server.py:1688
msgid "'Error: We only accept JSON here.'"
msgstr "'Erro: Nós só aceitamos JSON aqui."

#: gateone/core/server.py:1704
#, python-format
msgid "Error in WebSocket action, %s: %s (%s line %s)"
msgstr "Erro em ação WebSocket, %s : %s ( %s linha %s )"

#: gateone/core/server.py:1710
#, python-format
msgid "Client sent unknown WebSocket action: %s"
msgstr "Cliente enviou ação WebSocket desconhecido: %s"

#: gateone/core/server.py:1734
#, python-format
msgid "WebSocket closed (%s %s)."
msgstr "WebSocket fechado ( %s %s )."

#: gateone/core/server.py:1736
msgid "WebSocket closed (unknown user)."
msgstr "WebSocket fechado (usuário desconhecido)."

#: gateone/core/server.py:1765
msgid "WebSocket Latency: {0}ms"
msgstr "WebSocket Latência: {0} ms"

#: gateone/core/server.py:1883
msgid "API AUTH: Invalid API authentication object (missing api_key)."
msgstr "AUTH API: Invalid objeto de autenticação API (faltando api_key)."

#: gateone/core/server.py:1901 gateone/core/server.py:3782
#, python-format
msgid "API AUTH: Unsupported API auth signature method: %s"
msgstr "AUTH API: assinatura do método auth API não suportado: %s"

#: gateone/core/server.py:1908 gateone/core/server.py:3787
#, python-format
msgid "API AUTH: Unsupported API version: %s"
msgstr "AUTH API: API versão não suportado: %s"

#: gateone/core/server.py:1914
msgid "API AUTH: API Key not found."
msgstr "AUTH API: API Key não encontrado."

#: gateone/core/server.py:1923
msgid "API AUTH: Signature check failed."
msgstr "AUTH API: verificação de assinatura falhou."

#: gateone/core/server.py:1924
msgid "Got signature: {0}, expected: {1}"
msgstr "Tem assinatura: {0} , o esperado: {1}"

#: gateone/core/server.py:1935
#, python-format
msgid "API AUTH: replay attack detected!  User: %s, Remote IP: %s, Origin: %s"
msgstr "AUTH API: replay ataque detectado! Usuário: %s , IP remoto: %s , de Origem: %s"

#: gateone/core/server.py:1937
msgid "API AUTH: Replay attack detected!  This event has been logged."
msgstr "AUTH API: replay ataque detectado! Este evento foi registrado."

#: gateone/core/server.py:1946
msgid ""
"API AUTH: Authentication failed due to an expired auth object.  If you "
"just restarted the server this is normal (users just need to reload the "
"page).  If  this problem persists it could be a problem with the server's"
" clock (either this server or the server(s) embedding Gate One)."
msgstr "AUTH API: Falha de autenticação devido a um objeto auth expirado. Se você só reiniciou o servidor isso é normal (os usuários só precisa recarregar a página). Se o problema persistir, pode haver um problema com o relógio do servidor (este servidor ou o servidor (s) a incorporação Gate One)."

#: gateone/core/server.py:1954
msgid ""
"AUTH FAILED: Authentication object timed out. Try reloading this page "
"(F5)."
msgstr "AUTH FALHOU: objeto de autenticação expirou. Tente recarregar esta página (F5)."

#: gateone/core/server.py:1958
msgid ""
"AUTH FAILED: If the problem persists after reloading this page please "
"contact your server administrator to notify them of the issue."
msgstr "AUTH FALHA: Se o problema persistir depois de recarregar esta página, por favor contate o administrador do servidor para notificá-los do problema."

#: gateone/core/server.py:1964
msgid "API Authentication Successful"
msgstr "Autenticação da API de sucesso"

#: gateone/core/server.py:2055
msgid "Proxy in use: Client URL differs from server."
msgstr "Proxy em uso: URL do cliente difere do servidor."

#: gateone/core/server.py:2078 gateone/core/server.py:2085
msgid "Unauthenticated WebSocket attempt."
msgstr "Tentativa WebSocket não autenticado."

#: gateone/core/server.py:2125
msgid ""
"Client tried to use API-based authentication but this server is "
"configured with 'auth = \"{0}\"'.  Did you forget to set '\"auth\": "
"\"api\"' in the settings?"
msgstr "Cliente tentou usar a autenticação baseada em API, mas este servidor está configurado com 'auth = \ " {0} \ "." Você se esqueceu de definir '\ "auth \": \ "api \"' nas configurações?"

#: gateone/core/server.py:2130
msgid ""
"AUTHENTICATION ERROR: Server is not configured to perform API-based "
"authentication.  Did someone forget to set '\"auth\": \"api\"' in the "
"settings?"
msgstr "ERRO DE AUTENTICAÇÃO: Server não está configurado para realizar a autenticação baseada em API. Será que alguém se esqueça de definir '\ "auth \": \ "api \"' nas configurações?"

#: gateone/core/server.py:2158
msgid "Authentication failed for unknown user"
msgstr "Falha na autenticação de usuário desconhecido"

#: gateone/core/server.py:2159
msgid "AUTHENTICATION ERROR: User unknown"
msgstr "ERRO DE AUTENTICAÇÃO: Usuário desconhecido"

#: gateone/core/server.py:2179
msgid ""
"User {upn} authenticated successfully via origin {origin} (location: "
"{location})."
msgstr "Usuário {} upn autenticado com êxito via origem {origem} (localização: {local})."

#: gateone/core/server.py:2192
msgid "Please wait while the server is restarted..."
msgstr "Por favor, aguarde enquanto o servidor é reiniciado ..."

#: gateone/core/server.py:2233
msgid "Licensed user limit {max_users} exceeded: {user_count} connected users"
msgstr "Limite usuário licenciado {} MAX_USERS excedeu: {} USER_COUNT usuários conectados"

#: gateone/core/server.py:2619
msgid "Modification to theme file detected.  Theme will be recreated."
msgstr "Modificação de arquivo de tema detectado. Tema será recriado."

#: gateone/core/server.py:2727
#, python-format
msgid "No expired %s files at client %s"
msgstr "No expirado %s arquivos no cliente %s"

#: gateone/core/server.py:2730
#, python-format
msgid "Requesting deletion of expired files at client %s: %s"
msgstr "Solicitando exclusão de arquivos expirados no cliente %s : %s"

#: gateone/core/server.py:2786
msgid "File Request Error: File not found ({0})"
msgstr "Request File Erro: Arquivo não encontrado ( {0} )"

#: gateone/core/server.py:2899 gateone/core/server.py:3201
msgid "send_js is false; will not send JavaScript."
msgstr "send_js é falso; não enviará JavaScript."

#: gateone/core/server.py:2908 gateone/core/server.py:3131
msgid "send_css is false; will not send CSS."
msgstr "send_css é falso; não enviará CSS."

#: gateone/core/server.py:2977
#, python-format
msgid "send_js_or_css(): File not found: %s"
msgstr "send_js_or_css (): File not found: %s"

#: gateone/core/server.py:3062 gateone/core/server.py:3136
msgid "File does not exist: {0}"
msgstr "O arquivo não existe: {0}"

#: gateone/core/server.py:3297
#, python-format
msgid "Translation file, %s could not be found"
msgstr "Arquivo de tradução, %s não pôde ser encontrado"

#: gateone/core/server.py:3322
msgid "Error: No message to send."
msgstr "Erro: Nenhuma mensagem a ser enviada."

#: gateone/core/server.py:3325
msgid "Error: Missing UPN."
msgstr "Erro: Falta UPN."

#: gateone/core/server.py:3329
msgid "User Message: {0}"
msgstr "Mensagem: {0}"

#: gateone/core/server.py:3589
msgid ""
"In order to use Google authentication you must create a Google project "
"for your installation and add:\n"
"\t{\"google_oauth\": {\"key\": \"<YOUR CLIENT ID>\", \"secret\": \"<YOUR "
"CLIENT SECRET>\"}} to your 20authentication.conf (under the \"gateone\" "
"section)."
msgstr "Para utilizar a autenticação do Google você deve criar um projeto do Google para a sua instalação e adicione: \ n \ t {\ "google_oauth \": {\ "chave \": \ "<o ID do Cliente> \", \ "segredo \ "(seção gateone \": "\" <seu cliente SECRET> \ sob o \)}} à sua 20authentication.conf "."

#: gateone/core/server.py:3595
msgid ""
"To create a Google auth client ID and secret go to: "
"https://console.developers.google.com/ and click on \"APIs and Auth\".  "
"Then click \"Create New Client ID\". Set the \"JavaScript Origins\" value"
" to your Gate One server's address and the \"Redirect URIs\" to "
"https://<your Gate One server FQDN>/auth"
msgstr "Para criar uma ID de cliente auth Google e ir segredo para: https://console.developers.google.com/ e clique em \ "APIs e Auth \". Em seguida, clique em \ "Criar Novo Cliente ID \". Defina o "javascript Origins \" valor para o seu endereço Gate One do servidor eo \ "Redirect URI \" para https \: // <seu Gate One servidor FQDN> / auth"

#: gateone/core/server.py:3602
msgid ""
"For example, if your \"JavaScript Origins\" is: "
"https://gateone.example.com/"
msgstr "Por exemplo, se o seu \ "Javascript Origins \" é: https://gateone.example.com/"

#: gateone/core/server.py:3605
msgid "Your \"Redirect URIs\" would be: https://gateone.example.com/auth"
msgstr "Seu \ "Redirect URI \" seria: https://gateone.example.com/auth"

#: gateone/core/server.py:3615
#, python-format
msgid "Using %s authentication"
msgstr "Usando %s autenticação"

#: gateone/core/server.py:3617
msgid "No authentication method configured. All users will be ANONYMOUS"
msgstr "Nenhum método de autenticação configurado. Todos os usuários serão ANONYMOUS"

#: gateone/core/server.py:3709
#, python-format
msgid "Loaded global plugins: %s"
msgstr "Plugins globais carregado: %s"

#: gateone/core/server.py:3730
msgid ""
"\n"
"[1;31mAPI Authentication Failed![0m"
msgstr "\ N [1; Authentication 31mAPI falhou! [0m"

#: gateone/core/server.py:3731
#, python-format
msgid "Checking: %s"
msgstr "Verificação: %s"

#: gateone/core/server.py:3736
#, python-format
msgid "Not valid JSON: %s"
msgstr "Não é válido JSON: %s"

#: gateone/core/server.py:3750
#, python-format
msgid "You appear to be missing the following keys from your JSON object: %s"
msgstr "Você parece estar faltando as seguintes teclas do seu objeto JSON: %s"

#: gateone/core/server.py:3755
msgid "You don't appear to have any API keys configured."
msgstr "Você não parece ter quaisquer chaves de API configurados."

#: gateone/core/server.py:3756
msgid "Tip: You can create them on-demand via: gateone --new_api_key"
msgstr "Dica: Você pode criá-los sob demanda via: gateone --new_api_key"

#: gateone/core/server.py:3765
#, python-format
msgid "The given API key (%s) was not found."
msgstr "A chave API dado ( %s ) não foi encontrado."

#: gateone/core/server.py:3769
#, python-format
msgid "The given API key (%s) has no secret!"
msgstr "A chave API dado ( %s ) não tem segredo!"

#: gateone/core/server.py:3770
msgid "Your api_keys setting is probably not in the correct format."
msgstr "Sua configuração api_keys provavelmente não é no formato correto."

#: gateone/core/server.py:3771
msgid "The correct format is {\"api_keys\": {\"<API key>\":\"<secret>\"}}"
msgstr "O formato correto é {\ "api_keys \": {\ "<API key> \": \ "<segredo> \"}}"

#: gateone/core/server.py:3772
msgid ""
"It is recommended that you run 'gateone --new_api_key' and modify (or at "
"least look at) the resulting 30api_keys.conf"
msgstr "Recomenda-se que você execute 'gateone --new_api_key' e modificar (ou pelo menos olhar) o 30api_keys.conf resultando"

#: gateone/core/server.py:3794
#, python-format
msgid ""
"The generated signature (%s) does not match what was provided in the "
"given auth object (%s)"
msgstr "A assinatura gerada ( %s ) não coincide com o que foi oferecido no dado auth objeto ( %s )"

#: gateone/core/server.py:3816
msgid ""
"A license file is already installed.  Are you sure you want to replace "
"it? (y/n) "
msgstr "Um arquivo de licença já está instalado. Tem certeza de que deseja substituí-lo? (Y / n) "

#: gateone/core/server.py:3858
msgid ""
"Could not import pyelliptic which is required to validate licenses.  "
"Please install it:  sudo pip install pyelliptic"
msgstr "Não foi possível importar pyelliptic que é necessário para validar as licenças. Por favor, instale-o: sudo pip instalar pyelliptic"

#: gateone/core/server.py:3861
msgid "Or you could just download it: https://github.com/yann2192/pyelliptic"
msgstr "Ou você pode simplesmente baixá-lo: https://github.com/yann2192/pyelliptic"

#: gateone/core/server.py:3884
msgid "License for '{product}' has expired: {license}"
msgstr "Licença para '{produto}' expirou: {licença}"

#: gateone/core/server.py:3890
#, python-format
msgid "License has an invalid signature: %s"
msgstr "Licença possui uma assinatura inválida: %s"

#: gateone/core/server.py:3895
msgid "License for '{product}' will expire in less than 30 days: {license}"
msgstr "Licença para '{produto}' irá expirar em menos de 30 dias: {licença}"

#: gateone/core/server.py:3923
#, python-format
msgid "Could not find/create settings directory at %s"
msgstr "Não foi possível encontrar / criar diretório configurações em %s"

#: gateone/core/server.py:3935
msgid "Broadcast messages to users connected to Gate One."
msgstr "Transmitir mensagens aos usuários conectados ao Gate One."

#: gateone/core/server.py:3939
msgid "Install a commercial license for Gate One."
msgstr "Instale uma licença comercial para Gate One."

#: gateone/core/server.py:3943
msgid "Test API authentication by validating a JSON auth object."
msgstr "Autenticação API Teste, validando um objeto JSON auth."

#: gateone/core/server.py:3947
msgid ""
"You probably want to provide a different destination via "
"--log_file_prefix=/path/to/gateone.log"
msgstr "Você provavelmente vai querer oferecer um destino diferente via --log_file_prefix = / path / to / gateone.log"

#: gateone/core/server.py:3969 gateone/core/server.py:3977
#, python-format
msgid "Could not create log directory: %s"
msgstr "Não foi possível criar o diretório de log: %s"

#: gateone/core/server.py:4006
#, python-format
msgid "Could not write to the log: %s"
msgstr "Não foi possível gravar no log: %s"

#: gateone/core/server.py:4123
#, python-format
msgid "Unknown CLI command: '%s'"
msgstr "Comando CLI desconhecida: ' %s '"

#: gateone/core/server.py:4139
msgid "Imported applications: {0}"
msgstr "Aplicações importados: {0}"

#: gateone/core/server.py:4149
msgid "The configured 'uid' ({0}) does not exist."
msgstr "O 'uid' configurado ( {0} ) não existe."

#: gateone/core/server.py:4160
msgid "The configured 'gid' ({0}) does not exist."
msgstr "Configuradas 'gid' ( {0} ) não existe."

#: gateone/core/server.py:4165
msgid "Running as non-root; will not drop privileges."
msgstr "Executando como não-raiz; não vai cair privilégios."

#: gateone/core/server.py:4179
#, python-format
msgid ""
"Gate One could not create %s.  Please ensure that user, %s has permission"
" to create this directory or create it yourself and make user, %s its "
"owner."
msgstr "Gate One não foi possível criar %s . Certifique-se de que o usuário, %s tem permissão para criar este diretório ou criá-lo e fazer o usuário, %s seu dono."

#: gateone/core/server.py:4190
#, python-format
msgid "Failed to recursively change permissions of user_dir: %s, uid: %s, gid: %s"
msgstr "Falha ao alterar de forma recursiva permissões de user_dir: %s , uid: %s , gid: %s"

#: gateone/core/server.py:4203
#, python-format
msgid ""
"Error: Gate One could not create %s.  Please ensure that user, %s has "
"permission to create this directory or create it yourself and make user, "
"%s its owner."
msgstr "Erro: Gate One não foi possível criar %s . Certifique-se de que o usuário, %s tem permissão para criar este diretório ou criá-lo e fazer o usuário, %s seu dono."

#: gateone/core/server.py:4228
#, python-format
msgid "[1;31mERROR:[0m Could not create %s for log_file_prefix: %s"
msgstr "[1; 31mERROR: [0m Não foi possível criar %s para log_file_prefix: %s"

#: gateone/core/server.py:4230
msgid ""
"You probably want to change this option, run Gate One as root, or create "
"that directory and give the proper user ownership of it."
msgstr "Você provavelmente vai querer mudar esta opção, execute Gate One como root, ou criar o diretório e dar a posse do usuário adequado do mesmo."

#: gateone/core/server.py:4274
#, python-format
msgid "A new API key has been generated: %s"
msgstr "Uma nova chave de API foi gerado: %s"

#: gateone/core/server.py:4275
msgid "This key can now be used to embed Gate One into other applications."
msgstr "Esta chave pode agora ser usado para incorporar Gate One em outras aplicações."

#: gateone/core/server.py:4291
#, python-format
msgid "Version: %s (%s)"
msgstr "Versão: %s ( %s )"

#: gateone/core/server.py:4292
#, python-format
msgid "Tornado version %s"
msgstr "Tornado versão %s"

#: gateone/core/server.py:4310
#, python-format
msgid ""
"Connections to this server will be allowed from the following origins: "
"'%s'"
msgstr "As conexões a este servidor será permitido a partir das seguintes origens: ' %s '"

#: gateone/core/server.py:4327
msgid ""
"Gate One could not create {ssl_base} ({e}). Are you using the correct "
"--settings_dir?"
msgstr "Gate One não conseguiu criar {ssl_base} ({e}). Você está usando o --settings_dir correto?"

#: gateone/core/server.py:4331
msgid "No SSL private key found.  One will be generated."
msgstr "Sem chave privada SSL encontrado. Será gerada."

#: gateone/core/server.py:4335
msgid "No SSL certificate found.  One will be generated."
msgstr "Nenhum certificado SSL encontrado. Será gerada."

#: gateone/core/server.py:4340
msgid ""
"Logging is set to DEBUG.  Be aware that this will record the keystrokes "
"of all users.  Don't be evil!"
msgstr "O registro é definido para depuração. Esteja ciente de que isso irá gravar as teclas digitadas de todos os usuários. Não seja mau!"

#: gateone/core/server.py:4383
#, python-format
msgid ""
"PAM authentication is configured but you are not running Gate One as "
"root.  If the pam_service you've selected (%s) is configured to use "
"pam_unix.so for 'auth' (i.e. authenticating against /etc/passwd and "
"/etc/shadow) Gate One will not be able to authenticate all users.  It "
"will only be able to authenticate the user that owns the gateone.py "
"process.pam_service"
msgstr "Autenticação PAM está configurada, mas você não está rodando Gate One como root. Se o pam_service que você selecionou ( %s ) está configurado para usar pam_unix.so para 'auth' (ou seja, autenticar em / etc / passwd e / etc / shadow) Gate One não será capaz de autenticar todos os usuários. Ele só vai ser capaz de autenticar o usuário que possui o process.pam_service gateone.py"

#: gateone/core/server.py:4392
msgid "Gate One has been configured."
msgstr "Gate One foi configurado."

#: gateone/core/server.py:4399
msgid "Listening on Unix socket '{socketpath}'"
msgstr "Ouvir em socket '{socketpath}'"

#: gateone/core/server.py:4407 gateone/core/server.py:4425
msgid ""
"You have https_redirect *and* disable_ssl enabled.  Please pick one or "
"the other."
msgstr "Você tem https_redirect * e * disable_ssl habilitado. Por favor, escolher um ou outro."

#: gateone/core/server.py:4412
msgid "http://{addr}:80/ will be redirected to..."
msgstr "http: // {end}: 80 / será redirecionado para ..."

#: gateone/core/server.py:4417
msgid "Listening on {proto}{address}:{port}/"
msgstr "Ouvir em {proto} {endereço}: {porta} /"

#: gateone/core/server.py:4429
msgid "http://*:80/ will be redirected to..."
msgstr "http: // *: 80 / será redirecionado para ..."

#: gateone/core/server.py:4432
msgid "Listening on {proto}*:{port}/"
msgstr "Ouvir em {} proto *: {porta} /"

#: gateone/core/server.py:4460
msgid "Multiprocessing is disabled.  Performance will be sub-optimal."
msgstr "Multiprocessamento está desativado. O desempenho será abaixo do ideal."

#: gateone/core/server.py:4470
msgid ""
"Multiprocessing is not functional on this system.  Threading for all "
"async calls."
msgstr "Multiprocessamento não é funcional no sistema. Enfiando para todas as chamadas assíncronas."

#: gateone/core/server.py:4480
msgid "Shutting down asynchronous processes/threads..."
msgstr "Desligando processos assíncronos / threads ..."

#: gateone/core/server.py:4486
msgid "Process running with pid "
msgstr "Processo de execução com pid "

#: gateone/core/server.py:4492
msgid ""
"Could not listen on {address}:{port} (address:port is already in use by "
"another application)."
msgstr "Não foi possível ouvir em {endereço}: {porta} (endereço: porta já em uso por outro aplicativo)."

#: gateone/core/server.py:4497
msgid ""
"User '{user}' does not have permission to create a process listening on "
"{address}:{port}.  Typically only root can use ports < 1024."
msgstr "Usuário '{user}' não tem permissão para criar um processo de escuta no endereço {}: {porta}. Normalmente apenas o root pode usar portas <1024."

#: gateone/core/server.py:4505
msgid "An error was encountered trying to listen on {address}:{port}..."
msgstr "Foi encontrado um erro tentando ouvir em {endereço}: {porta} ..."

#: gateone/core/server.py:4509
msgid "Exception was: {0}"
msgstr "A exceção foi: {0}"

#: gateone/core/server.py:4511
msgid "Caught KeyboardInterrupt.  Killing sessions..."
msgstr "Preso KeyboardInterrupt. Matar sessões ..."

#: gateone/core/server.py:4515
msgid "Clearing cache_dir: {0}"
msgstr "Limpando cache_dir: {0}"

#: gateone/core/server.py:4519
msgid "pid file removed."
msgstr "arquivo pid removido."

#: gateone/core/utils.py:334
#, python-format
msgid "Could not write PID file: %s"
msgstr "Não foi possível gravar o arquivo PID: %s"

#: gateone/core/utils.py:369
msgid "ERROR: Timeout running shell command"
msgstr "ERRO: tempo limite de executar o comando shell"

#: gateone/core/utils.py:416
#, python-format
msgid "Error generating self-signed SSL key/certificate: %s"
msgstr "Geradora de erro auto-assinado de chave SSL / certificado: %s"

#: gateone/core/utils.py:457
#, python-format
msgid "Generating private key with command: %s"
msgstr "Gerando chave privada com o comando: %s"

#: gateone/core/utils.py:461
#, python-format
msgid ""
"An error occurred trying to create private SSL key:\n"
"%s"
msgstr "Ocorreu um erro ao tentar criar a chave SSL privada: \ n %s"

#: gateone/core/utils.py:466
#, python-format
msgid "Decrypting private key with command: %s"
msgstr "Decifrar chave privada com o comando: %s"

#: gateone/core/utils.py:470
#, python-format
msgid ""
"An error occurred trying to decrypt private SSL key:\n"
"%s"
msgstr "Ocorreu um erro ao tentar desencriptar a chave SSL privada: \ n %s"

#: gateone/core/utils.py:475
#, python-format
msgid "Creating CSR with command: %s"
msgstr "Criação de CSR com o comando: %s"

#: gateone/core/utils.py:479
#, python-format
msgid ""
"An error occurred trying to create CSR:\n"
"%s"
msgstr "Ocorreu um erro ao tentar criar CSR: \ n %s"

#: gateone/core/utils.py:486
#, python-format
msgid "Generating self-signed certificate with command: %s"
msgstr "Gerando certificado auto-assinado com o comando: %s"

#: gateone/core/utils.py:490
#, python-format
msgid ""
"An error occurred trying to create certificate:\n"
"%s"
msgstr "Ocorreu um erro ao tentar criar certificado: \ n %s"

#: gateone/core/utils.py:522
msgid ""
"Error: You do not have pyOpenSSL installed.  Please install it (sudo pip "
"install pyopenssl."
msgstr "Erro: Você não tem pyOpenSSL instalado. Por favor, instale-o (sudo pip instalar pyOpenSSL."

#: gateone/core/utils.py:622
#, python-format
msgid "Could not create directory: %s"
msgstr "Não foi possível criar diretório: %s"

#: gateone/core/utils.py:835
#, python-format
msgid ""
"Could not open pid_file (%s).  You *may* have to kill gateone.py manually"
" (probably not)."
msgstr "Não foi possível abrir pid_file ( %s ). Você * pode * ter que matar gateone.py manualmente (provavelmente não)."

#: gateone/core/utils.py:1426
#, python-format
msgid ""
"Error: Gate One does not have the ability to recursively chown %s to uid "
"%s/gid %s.  Please ensure that user, %s has write permission to the "
"directory."
msgstr "Erro: o Gate One não têm a capacidade de forma recursiva chown %s para uid %s / gid %s . Certifique-se de que o usuário, %s tem permissão de gravação para o diretório."

#: gateone/core/utils.py:1541 gateone/core/utils.py:1553
#, python-format
msgid "(saved ~%s bytes minifying %s)"
msgstr "(Salvo ~ %s bytes minifying %s )"

#: gateone/core/utils.py:1545
#, python-format
msgid "slimit failed trying to minify %s"
msgstr "SLIMIT falhou ao tentar apoucar %s"

#: gateone/core/utils.py:1656
#, python-format
msgid "Could not set supplemental groups: %s"
msgstr "Não foi possível definir grupos complementares: %s"

#: gateone/core/utils.py:1662
#, python-format
msgid "Could not set effective group id: %s"
msgstr "Não foi possível definir ID de grupo efetivo: %s"

#: gateone/core/utils.py:1667
#, python-format
msgid "Could not set effective user id: %s"
msgstr "Não foi possível definir ID de usuário efetivo: %s"

#: gateone/core/utils.py:1682
#, python-format
msgid ""
"Running as user/group, \"%s/%s\" with the following supplemental groups: "
"%s"
msgstr "Executando como usuário / grupo, \ " %s / %s \ "com os seguintes grupos complementares: %s"

